version: '3.4'

services:
  playershares.ui:
    image: ${DOCKER_REGISTRY-}playersharesui
    build:
      context: .
      dockerfile: Dockerfile_UI
    ports:
      - "20000:80"
    networks:
      - playershares-network  
    
  playershares.api:
    image: ${DOCKER_REGISTRY-}playersharesapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20001:80"
    networks:
      - playershares-network  

networks: 
  playershares-network:
        driver: bridge
